### PR TITLE
fix(bun-plugin): write the base CSS the imports resolve to

### PR DESCRIPTION
**Pull request by owjs3901**
## Two problems

**1. The plugin never wrote the file its own imports resolve to.**

`onResolve` maps every `devup-ui.css` import to `df/devup-ui/devup-ui.css`, but `writeDataFiles()` only created the *directory*. `codeExtract` returns the collected styles and `updatedBaseStyle`, and both were discarded:

```ts
const code = codeExtract(...)
return { contents: code.code, loader }   // css, cssFile, updatedBaseStyle dropped
```

So the plugin resolved imports to a path it never produced. It appeared to work only where another plugin had already left a file there. In a checkout without one - a fresh clone, a git worktree, CI - the first import fails to resolve and the run dies before any style is collected.

`plugin.test.ts` already spies on `getCss`, which the source never called.

**2. `registerShorthands` was called without being imported.**

Introduced in #632. The next, vite, rsbuild and webpack plugins all import it from `@devup-ui/wasm`; the bun plugin does not, so it throws `ReferenceError: registerShorthands is not defined` on startup. `bun test packages/bun-plugin` fails on `main` today for this reason.

## Change

- write the base stylesheet on `initialize`, so the first resolve has a target
- refresh it whenever `codeExtract` reports `updatedBaseStyle`, matching `webpack-plugin/src/loader.ts`
- import `registerShorthands` from `@devup-ui/wasm`

## Verification

```
bunx tsc --noEmit -p packages/bun-plugin   exit 0
bun test packages/bun-plugin               12 pass, 0 fail
bun run build                              exit 0
```

On `main` the same test command fails with the ReferenceError.

## How this surfaced

In another repository the frontend suite failed only outside the primary checkout:

```
Cannot find module 'C:\...\<main checkout>\df\devup-ui\devup-ui.css'
  from 'C:\...\<worktree>\...\ProjectRail.tsx'
```

It reproduced on an untouched worktree and on a clean clone of the same commit, and disappeared with `BUN_RUNTIME_TRANSPILER_CACHE_PATH=0` - Bun's transpiler cache is keyed by file content, so identical sources in a second checkout reused a resolution belonging to the first. That is only reachable because the resolved file is absent in the second checkout; once the plugin writes its own base stylesheet, each checkout resolves to a file it actually has.

### CODE REVIEW

**Comment by owjs3901** [comment]
Closing this: both claims in the description were wrong, and I verified that only after opening it.

**"The plugin never writes the base CSS its imports resolve to."**
Disproven. `df/devup-ui/devup-ui.css` does not exist in either the primary checkout or a second one, yet the consuming test suite passes in both. So resolution is not depending on that file, and the missing write is not what broke anything.

**"`registerShorthands` is called without being imported."**
Self-inflicted. `origin/main` at efbd436e already imports it; my own edit adding `getCss` to the same import block is what removed it. The ReferenceError I attributed to #632 was introduced by me in this branch.

The real symptom I started from - a second checkout resolving `devup-ui.css` to the first checkout's absolute path - disappeared once `node_modules` was reinstalled, which cleared Bun's transpiler cache. That points at cache staleness rather than at this plugin, and I no longer have a reproduction to justify a change here.

Sorry for the noise.
